name: E-Commerce Store CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci  

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          API_URL: ${{ secrets.API_URL }}
      
        

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Check for vulnerabilities
        run: npm audit --production --audit-level=high
        # Make this step continue even if it finds vulnerabilities
        continue-on-error: true

     
