name: E-Commerce Store CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Check code formatting
        run: npx prettier --check .
        
      - name: Lint
        run: npm run lint
        
     
        
      - name: Build
        run: npm run build
        env:
          # Add any environment variables needed for build
          NODE_ENV: development
          
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          
      - name: Check for vulnerabilities
        run: npm audit --production --audit-level=high
      
      
